app/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, send_file, url_for
from flask_login import login_required, current_user
from .models import Speech
from . import db
import json, io
from .create_doc import create_speech_doc

views = Blueprint('views', __name__)

@login_required
@views.route('/', methods=['GET', 'POST'])
def home():
  """Home view / create new speech route"""
  if request.method == 'POST':
    title = request.form.get('title')
    if len(title) < 1 or title.strip() == "":
      flash('Invalid title was entered', category='error')
    else:
      # Create new speech
      new_speech = Speech(title=title, data="none", user_id=current_user.id)
      db.session.add(new_speech)
      db.session.commit()
      flash('New Speech Created!', category='success')
    return render_template("home.html", user=current_user)
  # Render the home template only if the user if logged in
  if request.method == 'GET':
    if current_user and current_user.is_authenticated:
      return render_template("home.html", user=current_user)
    else:
      return redirect(url_for("auth.login"))

@views.route('/site-info', methods=['GET'])
def site_info():
  """Site info / tutorial view"""
  return render_template('site_info.html', user=current_user)

@login_required
@views.route('/delete-speech', methods=['POST'])
def delete_speech():
  """Delete speech route"""
  speech = Speech.query.get(json.loads(request.data)['speechId'])
  if speech:
    if speech.user_id == current_user.id:
      db.session.delete(speech)
      db.session.commit()
  return jsonify({})

@login_required
@views.route('/update-speech-title', methods=['POST'])
def update_speech_title():
  """Update speech route"""
  speech_data = json.loads(request.data)
  new_title = speech_data['newTitle']
  speech = Speech.query.get(speech_data['speechId'])
  if speech:
    if speech.user_id == current_user.id:
      speech.title = new_title
      db.session.commit()
  return jsonify({})

@login_required
@views.route('/load-speech', methods=['POST'])
def load_speech():
  """Load speech route"""
  speech = json.loads(request.data)
  speechId = speech['speechId']
  speech = Speech.query.get(speechId)
  if speech:
    if speech.user_id == current_user.id:
      current_user.current_speech_id = speechId
      db.session.commit()
  return jsonify({})

@login_required
@views.route('/save-speech', methods=['POST'])
def save_speech():
  """Save speech route"""
  speech = json.loads(request.data)
  speech_data = speech['speech_data']
  speech_id = speech['speech_id']
  speech = Speech.query.get(speech_id)
  if speech:
    if speech.user_id == current_user.id:
      speech.data = speech_data
      db.session.commit()
  return jsonify({})

@login_required
@views.route('/export-speech', methods=['GET'])
def export_speech():
  """Export speech route"""
  speech = Speech.query.get(current_user.current_speech_id)
  if speech:
    if speech.user_id == current_user.id:
      document = create_speech_doc(speech)
      f = io.BytesIO()
      document.save(f)
      f.seek(0)
      return send_file(f, as_attachment = True, download_name=speech.title + '.docx')
  return jsonify({})

@login_required
@views.route('/editor', methods=['GET'])
def editor():
  """Editor view"""
  if current_user:
    # Return to home if current speech doesn't exist
    if not Speech.query.get(current_user.current_speech_id):
      return redirect("/")
    speech = Speech.query.get(current_user.current_speech_id)
    return render_template("editor.html", user=current_user, speech=speech, stringified_data = json.dumps(speech.data))

app/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename="base.css")}}">
    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        {% if user.is_authenticated %}
          <div class="navbar-nav">
            <a class="navbar-brand" href="#">KVCC Speech Writer</a>
            <a class="nav-item nav-link" id="home" href="/">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          </div>
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link mx-auto" id="reset-password" href="/reset-password">Reset Password</a>
            <a class="nav-item nav-link" href="/">{{ user.username }}</a>
          </div>
        {% else %}
          <div class="navbar-nav">
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signup" href="/signup">Sign Up</a>
          </div>
        {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}
            <div class="alert alert-danger alert-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% else %}
            <div class="alert alert-success alert-dismissable fade show" role="alert">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}
    {% endblock %}

    <footer class="footer">
      <div class="container text-center">
        <span class="text-muted"><i class="bi bi-c-circle"></i> 2022 Nick Minnard</span>
      </div>
    </footer>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

app/templates/editor.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='editor_styles.css') }}">
    <title>Editor</title>
  </head>
  <body onload="init();">

    <div data-internalid={{speech.id}} id="speech-id"></div>
    <div data-internalid={{speech.data}} id="speech-data"></div>
    <div data-internalid='{{stringified_data}}' id="stringified-data"></div>

    <div class="sidebar">
      <div class="text-center">
        <a class="active" href="#/">KVCC Speech Writer</a>
      </div>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Save Speech" 
      data-content="Your speech is saved automatically but it never hurts to do save your progress as you work."
      id="save-speech-option" href="#/"><i class="bi bi-cloud-arrow-up"></i> Save Speech <span>[Ctrl+S]</span></a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Add Point" 
      data-content="A new point will be added directly underneath the one you select with the title you enter."
      id="add-point-option" href="#/"><i class="bi bi-plus-circle"></i> Add Point <span>[Ctrl+1]</span></a><hr>
      <a  tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Rename Point" 
      data-content="Will change the name of the point you select to what you enter."
      id="rename-point-option" href="#/"><i class="bi bi-pencil-square"></i> Rename Point <span>[Ctrl+2]</span></a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Shift Point Upt" 
      data-content="Will, if possible, move the point a level up."
      id="shift-point-up-option" href="#/"><i class="bi bi-arrow-up-square"></i> Shift Point Up <span>[Ctrl+3]</span></a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Shift Point Down" 
      data-content="Will, if possible, move the point a level down."
      id="shift-point-down-option" href="#/"><i class="bi bi-arrow-down-square"></i> Shift Point Down <span>[Ctrl+4]</span></a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Switch Sections" 
      data-content="Will switch the ENTIRE section that is highlighted after you select a point with the section of the second point you select."
      id="switch-section-option" href="#/"><i class="bi bi-arrow-left-right"></i> Switch Sections <span>[Ctrl+5]</span></a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Cancel Action" 
      data-content="Will cancel any above action (besides save speech) and reset the points."
      id="cancel-action-option" href="#/"><i class="bi bi-x-circle"></i> Cancel Action <span>[ESC]</span></a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Delete Point" 
      data-content="Will permanently delete the selected point, there is no undo or ctrl-z"
      id="delete-point-option" href="#/"><i class="bi bi-trash"></i> Delete Point</a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Download Word Doc" 
      data-content="Will download your speech in word document form."
      id="export-speech-option" href="/export-speech"><i class="bi bi-file-earmark-arrow-down"></i> Download Word Document</a><hr>
      <a tabindex="0" data-container="body" data-toggle="popover" data-placement="right" data-trigger="hover" title="Site Info" 
      data-content="Will redirect you to the site info / tutorial page."
      id="site-info-option" href="/site-info"><i class="bi bi-question-circle"></i> Site Info / Tutorial</a><hr>
    </div>

    <div class="content">
      <nav class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler mx-auto" type="button" data-toggle="collapse" data-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav mx-auto">
            <a class="navbar-brand" href="#">{{ speech.title }}</a>
          </div>
          <div class="navbar-nav ml-auto mr-5">
            <a class="nav-item nav-link" id="home" href="{{url_for('views.home')}}">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          </div>
        </div>
      </nav>

      <div id="points-container" class="container">
        <!--points will be generated here-->
      </div>

      <br><br><br><br><br>

    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous">
    </script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
    <script
      type="text/javascript"
      src="{{ url_for('static', filename='editor.js') }}"
    ></script>
  </body>
</html>

app/templates/forgot_password.html
{% extends "base.html" %}

{% block title %}Forgot Password{% endblock %}

{% block content %}
<div class="container">
  <form method="POST">
    <br>
    <h3 align="center">Generate New Password</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <p style="color:red;">As of right now there is a high chance the recovery email will be sent to your spam folder</p>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="container">
  <br>
  <h1 align="center">My Speeches</h1>
  <br><br>
  <div class="row border-bottom">
    <div class="col-3 d-flex justify-content-center align-items-center">
      <span><b>Title / Link</b></span>
    </div>
    <div class="col-3 d-flex justify-content-center align-items-center">
      <span><b>Last Updated On:</b></span>
    </div>
    <div class="col-3 d-flex justify-content-center align-items-center">
      <span><b>Created On:</b></span>
    </div>
    <div class="col-2 d-flex justify-content-center align-items-center">
      <span><b>Change Title</b></span>
    </div>
    <div class="col-1 d-flex justify-content-center align-items-center">
      <span><b>Delete</b></span>
    </div>
  </div>
  {% for speech in user.speeches %}
  <div class="row border-bottom py-2">
    <div class="col-3 d-flex justify-content-center align-items-center">
      <a class="btn-link" onclick="loadSpeech(document.getElementById('{{speech.id}}').id)" style="cursor: pointer;margin:auto;color:blue;text-decoration:underline;">{{ speech.title }}</a>
    </div>
    <div class="col-3 d-flex justify-content-center align-items-center">
      <span class="">{{ speech.get_updated() }}</span>
    </div>
    <div class="col-3 d-flex justify-content-center align-items-center">
      <span>{{ speech.get_created() }}</span>
    </div>
    <div class="col-2 p-1 d-flex justify-content-center align-items-center">
      <button class="btn btn-success" onclick="updateTitle(document.getElementById('{{speech.id}}').id)" style="border-radius:5px;">
        <i class="bi bi-pencil-square"></i> Edit Title
      </button>
    </div>
    <div class="col-1 d-flex justify-content-center align-items-center">
      <button type="button" id="{{speech.id}}" class="close" onclick="deleteSpeech(document.getElementById('{{speech.id}}').id)">
        <span aria-hidden="true"><i class="bi bi-trash"></i> </span>
      </button>
    </div>
  </div>
  {% endfor %}
  <br>
  <form method="POST">
    <div class="input-group">
      <input name="title" id="title" type="text" class="form-control" placeholder="Name of new speech">
    </div>
    <br>
    <div align="center">
      <button type="submit" class="btn btn-primary">Create New Speech</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container">
  <form method="POST">
    <br>
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input type="password" class="form-control" id="password" name="password" placeholder="Enter password">
    </div>
    <div class="text-center">
      <a class="btn-link" href="/forgot-password">Forgot Password</a>
      <br><br>
      <button type="submit" class="btn btn-primary">Login</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/reset_password.html
{% extends "base.html" %}

{% block title %}Reset Password{% endblock %}

{% block content %}
<div class="container">
  <form method="POST">
    <br>
    <h3 align="center">Reset Password</h3>
    <div class="form-group">
      <label for="password1">New Password</label>
      <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter new password">
    </div>
    <div class="form-group">
      <label for="password2">Confirm</label>
      <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password">
    </div>
    <br>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
</div>
{% endblock content %}

app/templates/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container">
  <form method="POST">
    <br>
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <div class="form-group">
      <label for="username">Username</label>
      <input type="text" class="form-control" id="username" name="username" placeholder="Enter Username">
    </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password">
    </div>
    <div class="form-group">
      <label for="password2">Confirm</label>
      <input type="password" class="form-control" id="password2" name="password2" placeholder="Retype password">
    </div>
    <br>
    <div class="text-center">
      <button type="submit" class="btn btn-primary">Sign Up</button>
    </div>
  </form>
</div>
{% endblock %}

app/templates/site_info.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='editor_styles.css') }}">
    <title>Site Info</title>
  </head>
  <body onload="init();">

    <div class="sidebar">
      <a class="active" href="#/">KVCC Speech Writer</a>
      <a href="/editor">Back to editor <i class="bi bi-arrow-return-left"></i></a><hr>
    </div>

    <div class="content">
      <nav class="navbar navbar-expand-lg navbar-light">
        <button class="navbar-toggler mx-auto" type="button" data-toggle="collapse" data-target="#navbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <div class="navbar-nav mx-auto">
            <a class="navbar-brand" href="#">Site Info / Tutorial</a>
          </div>
          <div class="navbar-nav ml-auto mr-5">
            <a class="nav-item nav-link" id="home" href="{{url_for('views.home')}}">Home</a>
            <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          </div>
        </div>
      </nav>

      <div id="points-container" class="container">
        <h4>Disclaimer</h4>
        <p class="info-p">This tool is still in process of being developed. There are bound to be bugs and mistakes.
          If you encounter one, or have any suggestions for how the site can be improved, please let
          your professor know.
        </p>
        <br><br>
        <p class="info-p">
          ...A walkthrough / tutorial will be added here in the future
        </p>
      </div>

    </div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>